app_default:
    resource: "@AppBundle/Resources/config/routing/default_routing.yml"
    prefix:   /default

app_default_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_order:
    resource: "@AppBundle/Resources/config/routing/order_routing.yml"
    prefix:   /order